### ISSUE TITLE
shiboken: win64: wrapInstance: fix pointer size 

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside-feedstock#32] opened 2017-05-29 09:32 UTC
I think this is fixed in newer versions of pyside. The patch is quite simple:
```
diff --git a/sources/shiboken/shibokenmodule/typesystem_shiboken.xml b/sources/shiboken/shibokenmodule/typesystem_shiboken.xml
index 6025400..4a0853c 100644
--- a/sources/shiboken/shibokenmodule/typesystem_shiboken.xml
+++ b/sources/shiboken/shibokenmodule/typesystem_shiboken.xml
@@ -17,7 +17,7 @@
         </inject-code>
     </add-function>
 
-    <add-function signature="wrapInstance(unsigned long, PyType)" return-type="PyObject*">
+    <add-function signature="wrapInstance(unsigned long long, PyType)" return-type="PyObject*">
         <inject-code>
             if (Shiboken::ObjectType::checkType((PyTypeObject*)%2))
                 %PYARG_0 = Shiboken::Object::newObject((SbkObjectType*)%2, (void*)%1, false, true);
```
Maybe this patch could be added to the feedstock and be applied for `# [win64]

https://bugreports.qt.io/browse/PYSIDE-191

**Comment by jschueller** [comment] 2017-05-29 14:20
This is marked duplicate of https://bugreports.qt.io/browse/PYSIDE-103 which is still valid.
I won't accept it here as is, unless you submit that patch upstream first.
They also mention size_t, what about it ?

**Comment by looooo** [comment] 2017-05-29 14:56
I know the better solution would be to have it fixed upstream, but as I expect not too much work to be done on the qt4 bindings, it would be simpler to patch it within the feedstock.

I will try size_t and upload a package for the freecad channel. thanks for the information.

**Comment by jschueller** [comment] 2017-05-29 14:59
The bug still exists for PySide2 (dev branch), so you know what to do... : )

**Comment by looooo** [comment] 2017-05-29 15:19
fork pyside : ).  I have no idea how to work with qt-projects. If pyside would be accesable via github, this wouldn't be a big problem... 
So I will let this open for someone experienced with contributing to qt-projects...

**Comment by jschueller** [comment] 2017-05-30 07:08
at least you can send an email to the (few) active maintainers

**Comment by jschueller** [comment] 2017-06-07 22:34
they replied: it was fixed in tree a long time ago!

**Closed as completed** 2017-06-08 17:23 UTC

**Comment by looooo** [comment] 2017-06-09 05:48
thanks!

**Comment by looooo** [comment] 2017-06-09 09:41
@jschueller there is another problem with shiboken. The diff is coming from @cgohlke who seems to have a working pyside for win10. Maybe this patch can be added to the merged one, as these patches address quite the same issue.
https://github.com/looooo/pyside-feedstock/blob/master/recipe/win_pointer_conversation_fix.patch

**Comment by jschueller** [comment] 2017-06-09 10:13
is it a new patch or is it already in tree ?

**Comment by looooo** [comment] 2017-06-09 10:35
I think it is allready in pyside2 but in a different way:

```
#if PY_MAJOR_VERSION >= 3
        if (!PyLong_Check(pyobj)) {
            PyErr_SetString(PyExc_TypeError, "Invalid type for unsigned long long conversion");
            return 0;
        }

        return PyLong_AsUnsignedLongLong(pyobj);
#else
        if (PyInt_Check(pyobj)) {
            long result = (unsigned PY_LONG_LONG) PyInt_AsLong(pyobj);
            if (result < 0) {
                PyErr_SetObject(PyExc_OverflowError, 0);
                return 0;
            } else
                return (unsigned PY_LONG_LONG) result;
        } else if (PyLong_Check(pyobj)) {
            return (unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLong(pyobj);
        } else {
            PyErr_SetString(PyExc_TypeError, "Invalid type for unsigned long long conversion");
            return 0;
        }
#endif // Python 2
    }
};
```

**Comment by jschueller** [comment] 2017-06-09 18:54
what bug does it fix ?

**Comment by looooo** [comment] 2017-06-09 19:22
I don't know which bug it fixes, but the python interface of shiboken has quite some problems without this fix. Without it Overflow Errors are reported on win10. This patch fix this problems.
There is no such issue with win 7 and linux.

**Comment by jschueller** [comment] 2017-06-09 19:25
@cgohlke do you know what's the problem ?

**Comment by cgohlke** [comment] 2017-06-09 20:06
Somewhere in the PySide headers ` PyInt_Check` is defined as `PyLong_Check` on Python 3 for compatibility reasons (Python 3 only has PyLong, not PyInt). So on 64-bit Python 3 the `if (PyInt_Check(pyobj)) {...}` block is run with 64-bit `PyLong` values even though the block can handle C `long` only (because it was meant for Python 2 PyInt). On Windows C `long` is always 32-bit. Hence the block returns wrong results on Windows when the 64-bit `PyLong` values are greater than 2**32. That can happen on Windows 7 too, it's just not that likely for pointers. On Python 3 the `if (PyInt_Check(pyobj)) {...}` block should be removed.  Hope I got it right...

**Comment by jschueller** [comment] 2017-06-10 06:25
Do you have a script that shows the bug ?

**Comment by cgohlke** [comment] 2017-06-10 06:27
https://github.com/looooo/pivy/issues/18#issuecomment-305956542
